### ISSUE TITLE
Fet req: put laslogin directly under settings menu and not under preferences section

### ISSUE THREAD

**Issue by mckaygerhard** [dsoares/Roundcube-Plugin-Lastlogin#19]
Currently the last login feature are located under the preferences section of the configuration settings menu in roundcube, i mean:
login->settings->preferences->laslogin

its possible to relocate or put directly unbder the settings menu directly or how i can doit that?
under settings menu and not under preferences section, i mean:
login->settings->laslogin

i tried but due i not have so much time at job maybe...

**Comment by dsoares** [comment]
Release [1.0.0](/dsoares/Roundcube-Plugin-Lastlogin/releases/tag/1.0.0) implements this feature.
