### ISSUE TITLE
Getting IP by geoiptool, don't save the real_ip

### ISSUE THREAD

**Issue by karlmendes** [dsoares/Roundcube-Plugin-Lastlogin#24]
Only the local IP has in DB.

**Comment by dsoares** [comment]
Sorry, i don't understand the issue.
Geoiptool from geoiptool.com is used in [geolocation plugin](https://plugins.roundcube.net/packages/dsoares/geolocation) only to get the `geoloc` information (city, region, country), not the IP. 
The `ip` and `real_ip` is calculated from the `$_SERVER` vars and it is based on Roundcube rcube_utils::remote_ip().

Can you explain the issue with more detail?

**Comment by karlmendes** [comment]
Yes, debugging i found the $_SERVER and the real_ip info isn't here, i dont know if because i use a VM for test.

i think i change the main plugin

hauahuah

thx
