### ISSUE TITLE
combine w blacklist: able to close other sessions (like gmail does with multisessions)

### ISSUE THREAD

**Issue by mckaygerhard** [dsoares/Roundcube-Plugin-Lastlogin#6]
i assume u are in similar position like me, have a job that uses rounducbe for enterprise like purposes

gmail can able to cloe sessiones opened that are not the active ..

if this plugin can be combined with blacklist plugin, can able to disables other sessions..

i think that in he ip list recent login table, added a button to others, marks activ in extra column, then se te $_SESSION object to difference the active sessions.. 

added hook that when refresh, invalidate the other sessions if user choose to close ohters sessions

a good idea, but mi knowledg of rouncube api are limited.. i can help of course..

**Comment by dsoares** [comment]
I'm sorry, i did not understand your comment. You may write it in spanish if you prefer, i can read spanish as well.
But if it is something like closing other opened sessions (like GMail does) it is completely out of the scope of this plugin.

**Comment by mckaygerhard** [comment]
odio el ingles... escribo en la consola y cometo muchos errores, ya que mi internet se va muy rapido y es inestable

si esta out of scope, si hacemos opcional que el plugin backlist guarde en database que ip/usuario/lugar es permitido, podemos desde el plugin lastlogin (u/o otro nuevo similar) ver el $_sessionid de todas las sesiones abiertas, e invalidarlo en el proximo refresh (se hay un "hook" para la recarga de verificacion de nuevos correos)

para ver otras sessiones ya abiertas, guardamos el $_sessionid en la (futura) columna de sesiones en el plugin de geolocation

**Comment by mckaygerhard** [comment]
hey, with the info in https://github.com/dsoares/Roundcube-Plugin-Geolocation/issues/1#issuecomment-228023098 i think i can doit this for intranet's

using cookie and ip from client we can revalidate session after hook login post!

if client want to close any other session, so mark invalid the macht! from the table of sessions in the lastlogin pĺugin
