### ISSUE TITLE
table insert for postgres not working, for older sesions in preferences!

### ISSUE THREAD

**Issue by mckaygerhard** [dsoares/Roundcube-Plugin-Lastlogin#9]
las login plugin work perfectly but i have a problem i noted that in preferences theres a table of lasted sessions opnened

so i suspech u use/made this plugin for specific intranet purposes, well, me too need intranet purposes..

so the table i get empty, how can i debug due in the logs directory of roundcube i not have any related error...

help me a little and i made the code changes! thanks in advance!

**Comment by mckaygerhard** [comment]
![error-lastlogin-roundcube](https://cloud.githubusercontent.com/assets/1571724/16276297/8e80ca48-3877-11e6-8ccf-284273dbee51.png)

**Comment by mckaygerhard** [comment]
i canot see any error, the insert statement query looks good, so help me someting and i'll able to provide some solution or support.. see you later i posted a fix for other problem. see the pull resquests!

**Comment by dsoares** [comment]
I think this is related to #10.
It's not the INSERT that is failing, it's the SELECT to load the information.
Please, change your PR as I say in https://github.com/dsoares/Roundcube-Plugin-Lastlogin/pull/11#issuecomment-228069363 and i'll merge it.

**Comment by mckaygerhard** [comment]
i'll changed and still not load, due i revised the table and no inserts where found!

**Comment by mckaygerhard** [comment]
rundcube has a write log , i'll see if can adapt and see some debug to search, and i'll post feedback later

**Comment by dsoares** [comment]
Please check if your plugin table (userlogins) was updated according to https://github.com/dsoares/Roundcube-Plugin-Lastlogin/blob/master/SQL/mysql/2016061600.sql

I put the SQL update scripts in `SQL/{mysql,postgres}/2016061600.sql` but i'm not sure that composer really uses them when it updates the packages (although i have this in `composer.json`

```json
    "extra": {
        "roundcube": {
            "sql-dir": "SQL"
        }

```

**Comment by mckaygerhard** [comment]
i tried in new clean environment, the update script are not related

i'm very bsy this weekend the monday i'll focused in that problem and
i promise will find something and post feedback

2016-06-23 14:31 GMT-04:00, dsoares <notifications@github.com>:
> Please check if your plugin table (userlogins) was updated according to
> https://github.com/dsoares/Roundcube-Plugin-Lastlogin/blob/master/SQL/mysql/2016061600.sql
>
> I put the SQL update scripts in `SQL/{mysql,postgres}/2016061600.sql` but
> i'm not sure that composer really uses them when it updates the packages
> (although i have this in `composer.json`
>
> ```json
>     "extra": {
>         "roundcube": {
>             "sql-dir": "SQL"
>         }
>
> ```
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dsoares/Roundcube-Plugin-Lastlogin/issues/9#issuecomment-228141926


-- 
Lenz McKAY Gerardo (PICCORO)
http://qgqlochekone.blogspot.com

**Comment by dsoares** [comment]
Do you still have this problem ?
If the table is empty, please verify that you have the option `log_logins` enabled in main roundcube configuration.

**Comment by mckaygerhard** [comment]
i just tested now in production and testing environments, does not write logs, 
in fact there's no log_logins option enabled, but in any way when enabled no differences was happened

i'll will made a testing environment with mysql in one mount to analice more and collaborate to make possible a plugin able to use with sqlite, postgres and mysql.. 

last i was very busy due roundcube related ajustments.. i'm not expert that's the fact but i'm working hard to make something, take me with patience and thanks of course

**Comment by dsoares** [comment]
Where did you enable the option `log_logins` ?

On Tue, Aug 9, 2016 at 2:25 PM, PICCORO Lenz McKAY <notifications@github.com

**Comment by mckaygerhard** [comment]
yeah currently revised the table and theres no rows, i must also revise the debug log, but the traffic between server and my office are very low now.. i deb that to you sorry ...

**Comment by dsoares** [comment]
But you did not answered my question. You said 
> but in any way when enabled no differences was happened
where did you enable the option `log_logins` ?

**Comment by mckaygerhard** [comment]
in themain config, of course, not in the plugin config, an not in the sample config or the default config files..

**Comment by mckaygerhard** [comment]
hello again, i see new commit about improve insert into table, i'm not tested with lasted commits.. i'll not see in details but if need i can made that try in next days... right now not due huge traffic in my job...

**Comment by dsoares** [comment]
Do you still have this problem? I'm going to close this if there's no feedback.

**Comment by mckaygerhard** [comment]
ok lest testing right now, sorry for late, note: i'll use complety new install of the plugin in and existing environment

**Comment by mckaygerhard** [comment]
seems the problem was around line lastlogin.php#L167 the value for tor column ..

i think my clone of git was bad due in last check still was in problem, now in a different machine i upload the clone and looks good, now i'll test agains the production server in roundcube 1.0.5 and post feedback here

**Comment by dsoares** [comment]
Thanks!
